export const TOGGLE_FLAG_SHOWCOLORSETTING = 'TOGGLE_FLAG_SHOWCOLORSETTING';
export const TOGGLE_FLAG_LOADSIGN = 'TOGGLE_FLAG_LOADSIGN';
export const SET_BROWSERUNSUPPORT = 'SET_BROWSERUNSUPPORT';
export const SET_IMGHASLOAD = 'SET_IMGHASLOAD';
export const SET_CROPPER = 'SET_CROPPER';
export const SET_CROPPERHASINIT = 'SET_CROPPERHASINIT';
export const SET_IMG = 'SET_IMG';
export const SET_USERNAME = 'SET_USERNAME';